repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: hadolint-docker
      name: Lint Dockerfiles
      description: Runs hadolint Docker image to lint Dockerfiles
      language: docker_image
      types: ["dockerfile"]
      entry: ghcr.io/hadolint/hadolint hadolint
